# Generated by Django 5.0.4 on 2024-05-27 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GazaResponse', '0013_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_in_time', models.DateTimeField(auto_now_add=True)),
                ('log_out_time', models.DateTimeField(blank=True, null=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.shelter')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
