# Generated by Django 5.0.4 on 2024-07-07 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GazaResponse', '0027_uploadeddocument_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_num', models.IntegerField()),
                ('ambulance_code', models.CharField(max_length=32)),
                ('paramedic_name', models.CharField(max_length=64)),
                ('paramedic_phone', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('casualty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_requests', to='GazaResponse.person')),
            ],
        ),
    ]
