# Generated by Django 5.0.4 on 2024-07-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0027_uploadeddocument_title'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_log',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.hospital'),
        ),
    ]
