# Generated by Django 5.0.7 on 2024-07-25 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0029_alter_person_birthday'),
        ('medical', '0004_ambulance_log_fees_ambulance_log_scanneddocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_log',
            name='status',
            field=models.CharField(blank=True, default='جارية', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance_log',
            name='ambulance_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='ambulance_log',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.hospital'),
        ),
        migrations.AlterField(
            model_name='ambulance_log',
            name='paramedic_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ambulance_log',
            name='paramedic_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
