# Generated by Django 5.0.7 on 2024-07-26 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0029_alter_person_birthday'),
        ('medical', '0005_ambulance_log_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_log',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambulance_log',
            name='companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='GazaResponse.person'),
        ),
    ]
