# Generated by Django 5.0.7 on 2024-07-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_ambulance_log_arrival_time_ambulance_log_companion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance_log',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance_log',
            name='status',
            field=models.CharField(blank=True, default='لم يحضر الإسعاف', max_length=64, null=True),
        ),
    ]
