# Generated by Django 5.0.7 on 2024-07-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0029_alter_person_birthday'),
        ('medical', '0007_alter_ambulance_log_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMedicalDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='medical_documents')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalDocuments', to='GazaResponse.person')),
            ],
        ),
    ]
