# Generated by Django 5.0.7 on 2024-07-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_diagnose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnose',
            old_name='Diagnose',
            new_name='diagnose',
        ),
        migrations.AddField(
            model_name='diagnose',
            name='diagnose_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
