# Generated by Django 5.0.7 on 2024-07-26 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0029_alter_person_birthday'),
        ('medical', '0010_rename_diagnose_diagnose_diagnose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('is_urgent', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('actual_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('ticketScannedDocs', models.FileField(blank=True, upload_to='medical_interventions_docs')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_Interventions', to=settings.AUTH_USER_MODEL)),
                ('caseResponsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Interventions_responsible', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medical_Interventions', to='GazaResponse.person')),
            ],
        ),
    ]
