# Generated by Django 5.0.7 on 2024-07-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_medical_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_intervention',
            name='status',
            field=models.CharField(default='جديد', max_length=32),
        ),
    ]
