# Generated by Django 5.0.7 on 2024-07-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_alter_medical_intervention_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_intervention',
            name='actual_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
