# Generated by Django 5.0.7 on 2024-07-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_alter_medical_intervention_actual_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_intervention',
            name='actual_date',
            field=models.DateField(blank=True),
        ),
    ]
