# Generated by Django 5.0.7 on 2024-07-26 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_alter_medical_intervention_actual_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Intervention_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('CommentScannedDocs', models.FileField(blank=True, upload_to='medical_interventions_docs')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medica_authorComments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medical_Intervention_comments', to='medical.medical_intervention')),
            ],
        ),
    ]
