# Generated by Django 5.0.4 on 2024-04-26 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('numOfFloors', models.IntegerField()),
                ('accessibility', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorateName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngoName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelterName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartmentNum', models.IntegerField()),
                ('apartmentCapacity', models.IntegerField()),
                ('apartmentAccessibility', models.BooleanField()),
                ('whichBuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.building')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='bGovernorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.governorate'),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('hEntity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.entity')),
                ('hGovernorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='Dontation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('itemsName', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('personWhoReceived', models.CharField(max_length=64)),
                ('toBuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReceivedGifts', to='GazaResponse.building')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Donors', to='GazaResponse.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('birthday', models.DateTimeField()),
                ('theType', models.CharField(max_length=10)),
                ('idNumber', models.CharField(max_length=14)),
                ('code', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('phoneNumber', models.CharField(max_length=14)),
                ('isDisabled', models.BooleanField()),
                ('hasCancer', models.BooleanField()),
                ('diagnosis', models.TextField()),
                ('scannedDocs', models.FileField(upload_to='')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.apartment')),
                ('pHospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.hospital')),
                ('personGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.group')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='bshelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buldings', to='GazaResponse.shelter'),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('status', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('ticketScannedDocs', models.FileField(upload_to='')),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonTickets', to='GazaResponse.person')),
                ('caseResponsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
