# Generated by Django 5.0.4 on 2024-05-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hasCancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='idNumber',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='isDisabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='scannedDocs',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='theType',
            field=models.CharField(max_length=64),
        ),
    ]
