# Generated by Django 5.0.4 on 2024-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0002_alter_person_birthday_alter_person_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='scannedDocs',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
