# Generated by Django 5.0.4 on 2024-05-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0003_alter_person_scanneddocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='building',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='entity',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='governorate',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hospital',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='shelter',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='scannedDocs',
            field=models.FileField(blank=True, upload_to='IDs'),
        ),
    ]
