# Generated by Django 5.0.4 on 2024-05-24 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0004_apartment_code_building_code_entity_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='code',
        ),
        migrations.RemoveField(
            model_name='governorate',
            name='code',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='code',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='code',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='ذكر', max_length=64),
        ),
        migrations.AddField(
            model_name='shelter',
            name='bGovernorate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.governorate'),
        ),
    ]
