# Generated by Django 5.0.4 on 2024-05-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0005_remove_building_capacity_remove_entity_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='isWorking',
            field=models.BooleanField(default=False),
        ),
    ]
