# Generated by Django 5.0.4 on 2024-05-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0006_shelter_isworking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='isWorking',
            field=models.BooleanField(default=True),
        ),
    ]
