# Generated by Django 5.0.4 on 2024-05-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0007_alter_shelter_isworking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='code',
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
