# Generated by Django 5.0.4 on 2024-05-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0008_remove_building_code_alter_building_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='GazaResponse.apartment'),
        ),
    ]
