# Generated by Django 5.0.4 on 2024-05-25 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0010_alter_apartment_whichbuilding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='GazaResponse.group'),
        ),
    ]
