# Generated by Django 5.0.4 on 2024-05-27 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0012_volunteerarrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GazaResponse.shelter')),
            ],
        ),
    ]
