# Generated by Django 5.0.4 on 2024-05-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0016_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='apartment',
            new_name='Shelter',
        ),
    ]
