# Generated by Django 5.0.4 on 2024-05-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0018_rename_shelter_location_shelter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerArrival',
        ),
    ]
