# Generated by Django 5.0.4 on 2024-05-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0019_delete_volunteerarrival'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
