# Generated by Django 5.0.4 on 2024-06-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0020_delete_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='ProfilePics'),
        ),
    ]
