# Generated by Django 5.0.4 on 2024-06-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0021_person_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='logOutLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('scannedDocs', models.FileField(blank=True, upload_to='IDs')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='GazaResponse.person')),
            ],
        ),
    ]
