# Generated by Django 5.0.4 on 2024-06-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0022_logoutlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoutlogs',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='logoutlogs',
            name='scannedDocs',
            field=models.FileField(blank=True, upload_to='LogOutLogs'),
        ),
    ]
