# Generated by Django 5.0.4 on 2024-06-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0023_alter_logoutlogs_date_alter_logoutlogs_scanneddocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='entryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='hostingStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
