# Generated by Django 5.0.4 on 2024-07-05 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0025_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='id_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='document',
            field=models.FileField(upload_to='uploaded_documents'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='GazaResponse.person'),
        ),
    ]
