# Generated by Django 5.0.4 on 2024-07-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GazaResponse', '0026_uploadeddocument_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
