# Generated by Django 5.0.4 on 2024-05-31 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GazaResponse', '0020_delete_tickets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('ticketScannedDocs', models.FileField(blank=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorTickets', to=settings.AUTH_USER_MODEL)),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonTickets', to='GazaResponse.person')),
                ('caseResponsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
