# Generated by Django 5.0.4 on 2024-05-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_tickets_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='CommentScannedDocs',
            field=models.FileField(blank=True, upload_to='Comments'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticketScannedDocs',
            field=models.FileField(blank=True, upload_to='Tickets'),
        ),
    ]
